apiVersion: v1
kind: Pod
metadata:
  name: postgress
  labels:
    tier: db-tier
spec:
  containers:
    - name: postgress
      image: postgress
      env:
        - name: POSTGRES_PASSWORD
          value: mysecretpassword